version: "3.1"

services:
  mariadb:
    image: mariadb
    command: --log-bin=fosho_binlog --binlog-format=ROW
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: fosho

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: always
